# ╔══╗╔╗─╔╗╔╗╔╗╔══╗╔════╗╔╗╔╗╔══╗─╔══╗╔══╗
# ╚╗╔╝║╚═╝║║║║║║╔═╝╚═╗╔═╝║║║║║╔╗╚╗╚╗╔╝║╔╗║
# ─║║─║╔╗─║║║║║║╚═╗──║║──║║║║║║╚╗║─║║─║║║║
# ─║║─║║╚╗║║╚╝║╚═╗║──║║──║║║║║║─║║─║║─║║║║
# ╔╝╚╗║║─║║╚╗╔╝╔═╝║──║║──║╚╝║║╚═╝║╔╝╚╗║╚╝║
# ╚══╝╚╝─╚╝─╚╝─╚══╝──╚╝──╚══╝╚═══╝╚══╝╚══╝
#
# Developer: @megajavadeveloper
# Studio: InvStudio
# Links: t.me/invstudio
#
play-sound: true # Звук при отправке уведомления
warning-sound: "BLOCK_NOTE_BLOCK_PLING" # Звук, который будет воспроизводиться при предупреждении
drop-time: 120 # Время в секундах, через которое дропнутые предметы будут удалены
message: "&cДропнутые предметы были удалены!" # Сообщение, которое будет отправлено в чат
warning-message: "&c&lВнимание! &fДропнутые предметы будут удалены через 30 секунд!" # Предупреждение